/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sibdex;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javafx.scene.web.PromptData;

/**
 *
 * @author Louis
 */
public final class securePrompt extends javax.swing.JDialog {
    
    private securePrompt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static String[] request(boolean usn, boolean pwd) throws SQLException {
        securePrompt sP = new securePrompt(new Frame(), true);
        sP.usnTextField.setEnabled(usn);
        sP.pwdTextField2.setEnabled(pwd);
        sP.setVisible(true);
        return new String[]  {
            sP.usnTextField.getText(), 
            sP.pwdTextField2.getText(), 
            sP.jComboBox1.getItemAt(sP.jComboBox1.getSelectedIndex())
        };
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        usnTextField = new javax.swing.JTextField();
        pwdTextField2 = new javax.swing.JPasswordField();
        validateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PSQL Log In");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUEST", "TRAINER", "SCIENTIST", "DEVMODE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);

        usnTextField.setToolTipText("Username");
        getContentPane().add(usnTextField);

        pwdTextField2.setToolTipText("Password");
        getContentPane().add(pwdTextField2);

        validateBtn.setText("Validate");
        validateBtn.setToolTipText("");
        validateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(validateBtn);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_validateBtnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField pwdTextField2;
    private javax.swing.JTextField usnTextField;
    private javax.swing.JButton validateBtn;
    // End of variables declaration//GEN-END:variables
}
